Adding licensing information
operate-first/ai-for-cloud-ops pull request #13
Opened 2022-12-01 21:33 UTC by saadullah01

As indicated in the issue: https://github.com/operate-first/ai-for-cloud-ops/issues/12, I have added the LICENSE file to the repo.

2022-12-01 21:34 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by:


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fai-for-cloud-ops).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/ai-for-cloud-ops/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-01 22:08 UTC, abyrne55 requested changes
Please change the name/year as shown, and then this is good to go

2022-12-01 22:08 UTC, abyrne55 commented on LICENSE
> +Copyright (c) 2019, Emre Ates
```suggestion
Copyright (c) 2022, Operate First Contributors
```

2022-12-01 23:46 UTC, saadullah01 commented
@abyrne55 I have updated the LICENSE file

2022-12-02 00:13 UTC, mtoslalibu approved these changes
Looks good!

2022-12-02 00:13 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/ai-for-cloud-ops/pull/13#pullrequestreview-1201827431" title="Approved">mtoslalibu</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fai-for-cloud-ops).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/ai-for-cloud-ops/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-05 20:23 UTC, abyrne55 commented
/label tide/merge-method-squash

2022-12-05 20:24 UTC, abyrne55 commented
/approve

Thanks @saadullah01!

2022-12-05 20:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/ai-for-cloud-ops/pull/13#issuecomment-1338121919" title="Approved">abyrne55</a>*, *<a href="https://github.com/operate-first/ai-for-cloud-ops/pull/13#pullrequestreview-1201827431" title="Approved">mtoslalibu</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fai-for-cloud-ops).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/ai-for-cloud-ops/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-05 20:24 UTC, abyrne55 approved these changes

2022-12-05 20:24 UTC, sesheta commented
[APPROVALNOTIFIER] This PR is **NOT APPROVED**

This pull-request has been approved by: *<a href="https://github.com/operate-first/ai-for-cloud-ops/pull/13#pullrequestreview-1205226443" title="Approved">abyrne55</a>*, *<a href="https://github.com/operate-first/ai-for-cloud-ops/pull/13#pullrequestreview-1201827431" title="Approved">mtoslalibu</a>*


The full list of commands accepted by this bot can be found [here](https://go.k8s.io/bot-commands?repo=operate-first%2Fai-for-cloud-ops).

<details open>
Needs approval from an approver in each of these files:

- **[OWNERS](https://github.com/operate-first/ai-for-cloud-ops/blob/main/OWNERS)**

Approvers can indicate their approval by writing `/approve` in a comment
Approvers can cancel approval by writing `/approve cancel` in a comment
</details>
<!-- META={"approvers":[]} -->

2022-12-05 20:41 UTC, merged